
services:
  master01:
    image: centos7/hadoop:ws
    container_name: master01
    hostname: master01
    extra_hosts:
      - "master02:172.28.0.9"
      - "slave01:172.28.0.10"
      - "slave02:172.28.0.11"
      - "slave03:172.28.0.12"
    networks:
      ws_net:
        ipv4_address: 172.28.0.8
    deploy:
      resources:
        limits:
          memory: 1536M
    stdin_open: true
    tty: true

  master02:
    image: centos7/hadoop:ws
    container_name: master02
    hostname: master02
    extra_hosts:
      - "master02:172.28.0.8"
      - "slave01:172.28.0.10"
      - "slave02:172.28.0.11"
      - "slave03:172.28.0.12"
    networks:
      ws_net:
        ipv4_address: 172.28.0.9
    deploy:
      resources:
        limits:
          memory: 1536M
    stdin_open: true
    tty: true

  slave01:
    image: centos7/hadoop:ws
    container_name: slave01
    hostname: slave01
    extra_hosts:
      - "master02:172.28.0.8"
      - "master02:172.28.0.9"
      - "slave02:172.28.0.11"
      - "slave03:172.28.0.12"
    networks:
      ws_net:
        ipv4_address: 172.28.0.10
    deploy:
      resources:
        limits:
          memory: 1536M
    stdin_open: true
    tty: true

  slave02:
    image: centos7/hadoop:ws
    container_name: slave02
    hostname: slave02
    extra_hosts:
      - "master02:172.28.0.8"
      - "master02:172.28.0.9"
      - "slave01:172.28.0.10"
      - "slave03:172.28.0.12"
    networks:
      ws_net:
        ipv4_address: 172.28.0.11
    deploy:
      resources:
        limits:
          memory: 1536M
    stdin_open: true
    tty: true

  slave03:
    image: centos7/hadoop:ws
    container_name: slave03
    hostname: slave03
    extra_hosts:
      - "master02:172.28.0.8"
      - "master02:172.28.0.9"
      - "slave01:172.28.0.10"
      - "slave02:172.28.0.11"
    networks:
      ws_net:
        ipv4_address: 172.28.0.12
    deploy:
      resources:
        limits:
          memory: 1536M
    stdin_open: true
    tty: true

networks:
  ws_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24